input = _{ SOI ~ term ~ EOI }

term = _{ abs | app | var | "(" ~ term ~ ")" }
abs = { ("λ" | "\\") ~ params ~ "." ~ term }
params = { var+ }
app = { app_term{2, } } // left assoc
app_term = _{ abs | var | "(" ~ term ~ ")" }
var = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHA | ASCII_DIGIT | "_" )* }



WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
COMMENT = _{ comment | block_comment }
comment = { "//" ~ (!NEWLINE ~ ANY)* ~ NEWLINE }
block_comment = { "/*" ~ (!"*/" ~ ANY)* ~ "*/" }
